FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_builder_rhel-9-golang-1.24-openshift-4.20 AS builder
WORKDIR /go/src/github.com/openshift/azure-disk-csi-driver
COPY . .
RUN make azuredisk ARCH=$(go env GOARCH) && cp _output/$(go env GOARCH)/azurediskplugin .

FROM quay-proxy.ci.openshift.org/openshift/ci:ocp_4.20_base-rhel9
COPY --from=builder /go/src/github.com/openshift/azure-disk-csi-driver/azurediskplugin /bin/azurediskplugin
RUN yum install -y util-linux e2fsprogs xfsprogs ca-certificates && yum clean all && rm -rf /var/cache/yum

LABEL description="Azure Disk CSI Driver"

ENTRYPOINT ["/bin/azurediskplugin"]
